//url list, one list per show.

var photos=[
    "url('/photos/moab/1.jpg')",
    "url('/photos/moab/2.jpg')",
    "url('/photos/moab/3.jpg')",
    "url('/photos/moab/4.jpg')",
    "url('/photos/moab/5.jpg')",
    "url('/photos/moab/6.jpg')",
    "url('/photos/moab/7.jpg')",
    "url('/photos/moab/8.jpg')",
    "url('/photos/moab/9.jpg')",
    "url('/photos/moab/10.jpg')",
    "url('/photos/moab/11.jpg')",
    "url('/photos/moab/12.jpg')",
    "url('/photos/moab/13.jpg')",
    "url('/photos/moab/14.jpg')",
    "url('/photos/moab/15.jpg')",
    "url('/photos/moab/16.jpg')",
    "url('/photos/moab/17.jpg')",
    "url('/photos/moab/18.jpg')",
    "url('/photos/moab/19.jpg')",
    "url('/photos/moab/20.jpg')",
    "url('/photos/moab/21.jpg')",
    "url('/photos/moab/22.jpg')",
    "url('/photos/moab/23.jpg')",
    "url('/photos/moab/24.jpg')",
    "url('/photos/moab/25.jpg')",
    "url('/photos/moab/26.jpg')"
];
// sans titre: mettre ''
var legendes = [
    'Voyage sur Mars - Moab',
    'Voyage sur Mars - Moab 2',
    'Eros sur mars - Moab 3',
    'Green river',
    'Green river 2',
    'Green river 3',
    'Green river 4',
    'Eau sur mars - Green river',
    'Moab 4',
    'Moab 5',
    'Moab 6',
    'Pierres et touristes - Moab',
    'Un peu de vie - Moab',
    'Dessert en coulisses de film',
    'Nids de pies',
    'Dessert en montagne',
    'Printemps',
    'Quête d\'eau',
    'Pas d\'eau',
    'Pas assez d\'eau',
    'Un autre année sèche',
    'Fairview',
    'Salt Lake City',
    'La vallée de Salt Lake',
    'La vallée de Salt Lake 2',
    'Salt Lake City au soir'
];

var delai = 4000; // delai between pictures in ms
